name: Continuous Integration
on: [push, pull_request]
jobs:
  test:
    name: Test Suite (${{ matrix.os }}, rust-${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            features: std
          - os: ubuntu-latest
            rust: nightly
            features: std,nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --no-fail-fast --no-default-features
      - name: Run tests (with features)
        run: cargo test --verbose --no-fail-fast --features "${{ matrix.features }}"
  miri:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Run tests
        run: cargo miri test --verbose --no-default-features
      - name: Run tests (with features)
        run: cargo miri test --verbose --all-features
